name: Create Release Build

# Trigger the workflow on push when a new tag is pushed to the repository
# Tag Pattern: vX.Y.Z(W)
# Version code: X.Y.Z
# Build Number: W
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+([0-9]+)+

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK to GitHub
      # Continue the job even if this step fails
      continue-on-error: true
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: app/build/outputs/apk/debug/app-debug.apk
        asset_name: app-debug.apk
        tag: ${{ github.ref }}
        overwrite: false
        body: 'APK for CatCompanionApp'
